name: GameScoreGenius CI/CD
on:
  push:
    branches: [master]

env:
  username: ${{ secrets.DOCKER_HUB_USERNAME }}
  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install NPM Packages
        run: npm ci

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist

  Tests:
    needs: [Setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: dist

      - name: Restore cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Deploy Check
        run: npm run deploy-check

  Update-Cloudfront:
    runs-on: ubuntu-latest
    needs: [Setup, Tests]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: dist

      - name: Update S3 Bucket and trigger Cloudfront to update changes
        run: npm run aws-deploy
